"""
Django settings for akaex project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from datetime import timedelta
from django.utils.translation import ugettext_lazy as _

import http.client

#DAHPNE FIX HEADER MAX LENGHT AND REQUEST MAX LINE LENGHT
from twisted.web.http import HTTPChannel
from twisted.protocols.basic import LineReceiver
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0))&^+97hx6ghpsek19^r!-63oelm2!ge76dw!&nm3!k8nhm@x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guardian',
    'akaex',
    "structure",
    "core",
    "auditlog",
    "evaluation",
    "planning",
    "study_plan",
    "person",
    "procedure",
    "titulation",
    "django_celery_beat"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# fix-akademos-etecsa
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ak_demos',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
       os.path.join(BASE_DIR, 'akaex/static'),
       # ... otras rutas estáticas de las aplicaciones van aquí ...
   ]

#######################################################
################## AKADEMOS SETTINGS ##################
#######################################################

# ALLOWED_HOSTS = ['127.0.0.1' , 'localhost', 'akademos.local.uci.cu', '10.36.32.248']
# INTERNAL_IPS = ['127.0.0.1']

# LOCATION_FIELD = {
#     'map.provider': 'openstreetmap',
#     'search.provider': 'nominatim',
# }

# CORS_ORIGIN_ALLOW_ALL = True

# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# CORS_ALLOWED_ORIGINS = [
#    "http://localhost:4200"
# ]

# GUARDIAN_RAISE_403 = True
# GUARDIAN_AUTO_PREFETCH = False
# GUARDIAN_MONKEY_PATCH = False

# LANGUAGES = (("en", _("English")), ("es", _("Spanish")))
# LOCALE_PATHS = (
#     os.path.join(BASE_DIR, 'locale'),
# )

# LANGUAGE_CODE = "es"
# TIME_ZONE = 'America/Havana'
# USE_I18N = True
# USE_L10N = True
# USE_TZ = True

# Rest Framework
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
#     'DEFAULT_PAGINATION_CLASS': 'core.pagination.AkLimitOffsetPagination',
#     # 'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesLimitOffsetPagination',
#     'PAGE_SIZE': 100,
#     #'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
#     'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
#     'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',
#                                 'rest_framework_datatables.filters.DatatablesFilterBackend'),
#     'DEFAULT_PARSER_CLASSES': (
#         'rest_framework.parsers.JSONParser',
#         'rest_framework.parsers.MultiPartParser',
#     ),
#     "TEST_REQUEST_DEFAULT_FORMAT": "json",
# }
# PAGE_SIZE_UNLIMIT=15000

# SWAGGER_SETTINGS = {
#     'SECURITY_DEFINITIONS': {
#         'api_key': {
#             'type': 'apiKey',
#             'name': 'Autorization ',
#             'in': 'header'
#         }
#     }
# }

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Havana'

# JASPER_URL = 'http://localhost:8484'  # url donde esté corriendo jasper server
# JASPER_USER = 'jasperadmin'
# JASPER_PASSWORD = 'jasperadmin'

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
#     'ROTATE_REFRESH_TOKENS': False,
#     'BLACKLIST_AFTER_ROTATION': True,

#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'VERIFYING_KEY': None,
#     'AUDIENCE': None,
#     'ISSUER': None,

#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',

#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',

#     'JTI_CLAIM': 'jti',

#     'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
#     'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
#     'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
# }

# SENTRY_ENVIRONMENT = 'production'
# EMAIL_FROM = 'fortes@uci.cu'
# BASE_SITE_URL = 'http://server.akademos.mined.gob.cu'
# CLIENT_SITE_URL_LOGIN = 'http://akademos.mined.gob.cu'

# # Increase the the maximum number of parameters that may be received via GET or POST
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000
# DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760

# # Increase the limit of the header size
# http.client._MAXLINE = 1024000000

# HTTPChannel.totalHeadersSize = 1024000000
# LineReceiver.MAX_LENGTH = 1024000000