APP_LABEL = 'PLAN_ESTUDIO'

SCHOOL_PERIOD = {
    'PERIOD_PREPARATORY': 'PERIOD_PREPARATORY',
    'PERIOD_SECOND_YEAR_OF_LIFE': 'PERIOD_SECOND_YEAR_OF_LIFE',
    'PERIOD_THIRD_YEAR_OF_LIFE': 'PERIOD_THIRD_YEAR_OF_LIFE',
    'PERIOD_SECOND_FORTH_OF_LIFE': 'PERIOD_FORTH_YEAR_OF_LIFE',
    'PERIOD_FIFTH_YEAR_OF_LIFE': 'PERIOD_FIFTH_YEAR_OF_LIFE',
    'PERIOD_SIXTH_YEAR_OF_LIFE': 'PERIOD_SIXTH_YEAR_OF_LIFE',
    'PERIOD_PRESCHOOL': 'PERIOD_PRESCHOOL',
    'PERIOD_FIRST_YEAR': 'PERIOD_FIRST_YEAR',
    'PERIOD_SECOND_YEAR': 'PERIOD_SECOND_YEAR',
    'PERIOD_THIRD_YEAR': 'PERIOD_THIRD_YEAR',
    'PERIOD_FORTH_YEAR': 'PERIOD_FORTH_YEAR',
    'PERIOD_FIFTH_YEAR': 'PERIOD_FIFTH_YEAR',
    'PERIOD_SIXTH_YEAR': 'PERIOD_SIXTH_YEAR',
    'PERIOD_FIRST_GRADE': 'PERIOD_FIRST_GRADE',
    'PERIOD_SECOND_GRADE': 'PERIOD_SECOND_GRADE',
    'PERIOD_THIRD_GRADE': 'PERIOD_THIRD_GRADE',
    'PERIOD_FORTH_GRADE': 'PERIOD_FORTH_GRADE',
    'PERIOD_FIFTH_GRADE': 'PERIOD_FIFTH_GRADE',
    'PERIOD_SIXTH_GRADE': 'PERIOD_SIXTH_GRADE',
}

ACADEMIC_YEAR = {
    'FIRST_YEAR': 'FIRST_YEAR',
    'SECOND_YEAR': 'SECOND_YEAR',
    'THIRD_YEAR': 'THIRD_YEAR',
    'FORTH_YEAR': 'FORTH_YEAR',
    'FIFTH_YEAR': 'FIFTH_YEAR',
    'SIXTH_YEAR': 'SIXTH_YEAR',
}

CYCLE = {
    'FIRST_CYCLE': 'FIRST_CYCLE',
    'SECOND_CYCLE': 'SECOND_CYCLE',
}

STUDY_MODALITY = {
    'MODALITY_PRESENTIAL': 'MODALITY_PRESENTIAL',
    'MODALITY_SEMI_PRESENTIAL': 'MODALITY_SEMI_PRESENTIAL',
    'MODALITY_FROM_DISTANCE': 'MODALITY_FROM_DISTANCE',
}

COURSE_TYPE = {
    'COURSE_REGULAR_DAY': 'COURSE_REGULAR_DAY',
    'COURSE_BY_MEETINGS': 'COURSE_BY_MEETINGS',
}

SCALE_RANGE = {
    'SCALE_RANGE_M': 'SCALE_RANGE_M',
    'SCALE_RANGE_R': 'SCALE_RANGE_R',
    'SCALE_RANGE_B': 'SCALE_RANGE_B',
    'SCALE_RANGE_E': 'SCALE_RANGE_E',
}