from django.utils.translation import gettext_lazy as _


# ------------------- CONST TEACHING STATUS TYPES ------------------------
CONST_TEACHING_STATUS_UNDEFINED = 'UNDEFINED'
CONST_TEACHING_STATUS_REGISTRATION = 'REGISTRATION'
CONST_TEACHING_STATUS_TRANSFER = 'TRANSFER'
CONST_TEACHING_STATUS_PLACEMENT = 'PLACEMENT'
CONST_TEACHING_STATUS_GRADUATION = 'GRADUATION'
CONST_TEACHING_STATUS_UNSUBSCRIBE = 'UNSUBSCRIBE'
CONST_TEACHING_STATUS_ENROLLMENT = 'ENROLLMENT'
CONST_TEACHING_STATUS_STUDY_CONTINUITY = 'STUDY_CONTINUITY'
CONST_TEACHING_STATUS_CHANGE_OF_EDUCATION = 'CHANGE_OF_EDUCATION'


# ------------------- CONST PROCEDURE TYPES ------------------------

CONST_PROCEDURE_NONE = 'UNDEFINED'
CONST_PROCEDURE_UNSUBSCRIBE = 'UNSUBSCRIBE'
CONST_PROCEDURE_CHANGE_OF_EDUCATION = 'CHANGE_OF_EDUCATION'
CONST_PROCEDURE_ENROLLMENT = 'ENROLLMENT'
CONST_PROCEDURE_REGISTRATION = 'REGISTRATION'
CONST_PROCEDURE_TRANSFER = 'TRANSFER'
CONST_PROCEDURE_PLACEMENT = 'PLACEMENT'
CONST_PROCEDURE_PLACEMENT_BY_REGISTRATION = 'PLACEMENT_BY_REGISTRATION'
CONST_PROCEDURE_PLACEMENT_BY_TRANSFER = 'PLACEMENT_BY_TRANSFER'
CONST_PROCEDURE_PLACEMENT_BY_CHANGE_OF_EDUCATION = 'PLACEMENT_BY_CHANGE_OF_EDUCATION'
CONST_PROCEDURE_PLACEMENT_BY_STUDY_CONTINUITY = 'PLACEMENT_BY_STUDY_CONTINUITY'
CONST_PROCEDURE_PLACEMENT_BY_UNSUBSCRIBE = 'PLACEMENT_BY_UNSUBSCRIBE'

CONST_PROCEDURE_ECONOMIC_LENDING = 'ECONOMIC_LENDING'
CONST_PROCEDURE_ECONOMIC_LENDING_ENDING = 'ECONOMIC_LENDING_ENDING'
CONST_PROCEDURE_CHANGE_OF_FUNCTIONS_ENDING = 'CHANGE_OF_FUNCTIONS_ENDING'
CONST_PROCEDURE_CHANGE_OF_FUNCTIONS = 'CHANGE_OF_FUNCTIONS'
CONST_PROCEDURE_CHANGE_OF_JOB_POSITION = 'CHANGE_OF_JOB_POSITION'
CONST_PROCEDURE_CHANGE_OF_GROUP = 'CHANGE_OF_GROUP'
CONST_PROCEDURE_CHANGE_OF_SCHOOL_PERIOD = 'CHANGE_OF_SCHOOL_PERIOD'
CONST_PROCEDURE_ENROLLMENT_RATIFICATION = 'ENROLLMENT_RATIFICATION'
CONST_PROCEDURE_GRADUATION = 'GRADUATION'
CONST_STUDY_CONTINUITY = 'STUDY_CONTINUITY'


# ------------------- TEACHING STATUS CHOICES ----------------------


TEACHING_STATUS_TYPE = (
    (CONST_TEACHING_STATUS_UNDEFINED, _(CONST_TEACHING_STATUS_UNDEFINED)),
    (CONST_TEACHING_STATUS_REGISTRATION, _(CONST_TEACHING_STATUS_REGISTRATION)),
    (CONST_TEACHING_STATUS_TRANSFER, _(CONST_TEACHING_STATUS_TRANSFER)),
    (CONST_TEACHING_STATUS_PLACEMENT, _(CONST_TEACHING_STATUS_PLACEMENT)),
    (CONST_TEACHING_STATUS_GRADUATION, _(CONST_TEACHING_STATUS_GRADUATION)),
    (CONST_TEACHING_STATUS_UNSUBSCRIBE, _(CONST_TEACHING_STATUS_UNSUBSCRIBE)),
    (CONST_TEACHING_STATUS_ENROLLMENT, _(CONST_TEACHING_STATUS_ENROLLMENT)),
    (CONST_TEACHING_STATUS_STUDY_CONTINUITY, _(CONST_TEACHING_STATUS_STUDY_CONTINUITY)),
    (CONST_TEACHING_STATUS_CHANGE_OF_EDUCATION, _(CONST_TEACHING_STATUS_CHANGE_OF_EDUCATION))
)

# ------------------- PROCEDURE TYPES CHOICES ----------------------

STUDENT_PROCEDURE_TYPE = (

    (CONST_PROCEDURE_REGISTRATION, _(CONST_PROCEDURE_REGISTRATION)),
    (CONST_PROCEDURE_PLACEMENT_BY_REGISTRATION, _(CONST_PROCEDURE_PLACEMENT_BY_REGISTRATION)),
    (CONST_PROCEDURE_PLACEMENT_BY_TRANSFER, _(CONST_PROCEDURE_PLACEMENT_BY_TRANSFER)),
    (CONST_PROCEDURE_PLACEMENT_BY_CHANGE_OF_EDUCATION, _(CONST_PROCEDURE_PLACEMENT_BY_CHANGE_OF_EDUCATION)),
    (CONST_PROCEDURE_PLACEMENT_BY_STUDY_CONTINUITY, _(CONST_PROCEDURE_PLACEMENT_BY_STUDY_CONTINUITY)),
    (CONST_PROCEDURE_PLACEMENT_BY_UNSUBSCRIBE, _(CONST_PROCEDURE_PLACEMENT_BY_UNSUBSCRIBE)),
    (CONST_PROCEDURE_ENROLLMENT, _(CONST_PROCEDURE_ENROLLMENT)),
    (CONST_PROCEDURE_TRANSFER, _(CONST_PROCEDURE_TRANSFER)),
    (CONST_PROCEDURE_CHANGE_OF_EDUCATION, _(CONST_PROCEDURE_CHANGE_OF_EDUCATION)),
    (CONST_PROCEDURE_UNSUBSCRIBE, _(CONST_PROCEDURE_UNSUBSCRIBE)),
    (CONST_PROCEDURE_NONE, _(CONST_PROCEDURE_NONE)),
    (CONST_PROCEDURE_CHANGE_OF_GROUP, _(CONST_PROCEDURE_CHANGE_OF_GROUP)),
    (CONST_PROCEDURE_CHANGE_OF_SCHOOL_PERIOD, _(CONST_PROCEDURE_CHANGE_OF_SCHOOL_PERIOD)),
    (CONST_PROCEDURE_ENROLLMENT_RATIFICATION, _(CONST_PROCEDURE_ENROLLMENT_RATIFICATION)),
    (CONST_PROCEDURE_GRADUATION, _(CONST_PROCEDURE_GRADUATION)),
    (CONST_STUDY_CONTINUITY, _(CONST_STUDY_CONTINUITY))

)

PROCEDURE_PLACEMENT_TYPE = (
    (CONST_PROCEDURE_PLACEMENT_BY_REGISTRATION, _(CONST_PROCEDURE_PLACEMENT_BY_REGISTRATION)),
    (CONST_PROCEDURE_PLACEMENT_BY_TRANSFER, _(CONST_PROCEDURE_PLACEMENT_BY_TRANSFER)),
    (CONST_PROCEDURE_PLACEMENT_BY_CHANGE_OF_EDUCATION, _(CONST_PROCEDURE_PLACEMENT_BY_CHANGE_OF_EDUCATION)),
    (CONST_PROCEDURE_PLACEMENT_BY_STUDY_CONTINUITY, _(CONST_PROCEDURE_PLACEMENT_BY_STUDY_CONTINUITY)),
    (CONST_PROCEDURE_PLACEMENT_BY_UNSUBSCRIBE, _(CONST_PROCEDURE_PLACEMENT_BY_UNSUBSCRIBE)),
)

WORKER_PROCEDURE_TYPE = (
    
    (CONST_PROCEDURE_REGISTRATION, _(CONST_PROCEDURE_REGISTRATION)),
    (CONST_PROCEDURE_UNSUBSCRIBE, _(CONST_PROCEDURE_UNSUBSCRIBE)),
    (CONST_PROCEDURE_ECONOMIC_LENDING, _(CONST_PROCEDURE_ECONOMIC_LENDING)),
    (CONST_PROCEDURE_CHANGE_OF_FUNCTIONS, _(CONST_PROCEDURE_CHANGE_OF_FUNCTIONS)),
    (CONST_PROCEDURE_ECONOMIC_LENDING_ENDING, _(CONST_PROCEDURE_ECONOMIC_LENDING_ENDING)),
    (CONST_PROCEDURE_CHANGE_OF_FUNCTIONS_ENDING, _(CONST_PROCEDURE_CHANGE_OF_FUNCTIONS_ENDING)),
    (CONST_PROCEDURE_CHANGE_OF_JOB_POSITION, _(CONST_PROCEDURE_CHANGE_OF_JOB_POSITION))
)

# ------------------- PROCEDURE STATES ----------------------


CONST_PROCEDURE_STATE_INITIATED = 'INITIATED'
CONST_PROCEDURE_STATE_INPROCESS = 'INPROCESS'
CONST_PROCEDURE_STATE_FINISHED = 'FINISHED'
CONST_PROCEDURE_STATE_CANCELED = 'CANCELED'


PROCEDURE_REASON = {
    'REASON_ANOTHER_MUNICIPALITY_CENTER': 'REASON_ANOTHER_MUNICIPALITY_CENTER',
    'REASON_ANOTHER_MUNICIPALITY_OF_THE_PROVINCE': 'REASON_ANOTHER_MUNICIPALITY_OF_THE_PROVINCE',
    'REASON_ANOTHER_PROVINCE': 'REASON_ANOTHER_PROVINCE',
}

WAY_OF_ENTRY = {
    'WAY_ATTITUDE_TEST': 'WAY_ATTITUDE_TEST',
    'WAY_ENTRY_TEST': 'WAY_OF_ENTRY_ENTRY_TEST',
    'WAY_CONTINUITY_OF_STUDY': 'WAY_CONTINUITY_OF_STUDY',
    'WAY_CONTEST': 'WAY_CONTEST',
    'WAY_GRANT': 'WAY_GRANT',
}

ENROLLMENT_CONDITION_TYPE = {
    'CONDITION_INTERNAL': 'CONDITION_INTERNAL',
    'CONDITION_EXTERNAL': 'CONDITION_EXTERNAL',
    'CONDITION_SEMI_INTERNAL': 'CONDITION_SEMI_INTERNAl',
}

PROCEDURE_STATES = (
    (CONST_PROCEDURE_STATE_INITIATED,_(CONST_PROCEDURE_STATE_INITIATED)),
    (CONST_PROCEDURE_STATE_INPROCESS,_(CONST_PROCEDURE_STATE_INPROCESS)),
    (CONST_PROCEDURE_STATE_FINISHED,_(CONST_PROCEDURE_STATE_FINISHED)),
    (CONST_PROCEDURE_STATE_CANCELED, _(CONST_PROCEDURE_STATE_CANCELED))
)

PROCEDURE_STATES_TRANSLATED = {
    CONST_PROCEDURE_STATE_INITIATED: 'Iniciado',
    CONST_PROCEDURE_STATE_INPROCESS: 'En proceso',
    CONST_PROCEDURE_STATE_FINISHED: 'Terminado',
    CONST_PROCEDURE_STATE_CANCELED: 'Cancelado'
}

APP_LABEL = 'TRAMITE'

values_to_students_list = ['id', 'student__id','student__person__id', 'student__person__name', 'student__person__second_name',
                'student__person__first_last_name', 'student__person__second_last_name', 'student__person__ci',
                'student__person__ci_serie', 'student__person__race__id', 'student__person__race__name',
                'student__person__date_of_birth', 'student__person__gender__id', 'student__person__gender__name',
                'school_center__id', 'school_center__name',
                'school_center__province__id', 'school_center__province__name',
                'school_center__municipality__id', 'school_center__municipality__name',
                'school_center__educational_center_type__id',
                'school_center__educational_center_type__name', 'state__id', 'state__name',
                'school_situation__id', 'school_situation__name',
                'school_period__id', 'school_period__name', 'study_plan_organization__id',
                'study_plan_organization__name', 'category__id', 'category__name',
                'study_modality__id', 'study_modality__name', 'course_type__id', 'course_type__name',
                'enrollment_condition__id', 'enrollment_condition__name', 'way_entry__id', 'way_entry__name',
                'enrollment_tome', 'enrollment_folio', 'enrollment_number', 'photo', 'student__person__photo',
                'study_group__id', 'study_group__name', 'study_plan_version__id', 'study_plan_version__name',
                'academic_year__id', 'academic_year__name',
                'speciality__speciality__id', 'speciality__speciality__name', 'previous_procedure__id',
                'school_center__certification_groups__id', 'school_center__certification_groups__name',
                'organizational_unit__id',
                'organizational_unit__name',
                'education_type__id', 
                'education_type__name',
                'education_level_type__id', 
                'education_level_type__name',
                'activity__name', 
                'activity__id', 
                'previous_procedure__state',
                'school_center__educational_center_type__organism__id', 'school_center__educational_center_type__organism__name',
                'current_school_course__id', 
                'current_school_course__name', 
                'nationality__id', 
                'nationality__name',
                'procedure_type']


order_by_to_students_list = ['student__person__name', 'student__person__ci', 
    'school_center__name', 'state__name', 'speciality__speciality__name',
    'school_situation__name', 'school_period__name', 'study_group__name']
