from django.utils.translation import gettext_lazy as _

PERSON_STUDENT = 'Student'
PERSON_WORKER = 'Worker'
PERSON_TEACHER = 'Teacher'

NOM_TYPE = {
    'EYES_COLOR': 'EYES_COLOR',
    'HAIR_COLOR': 'HAIR_COLOR',
    'GENDER': 'GENDER',
    'QUALIFICATION_TYPE': 'QUALIFICATION_TYPE',
    'SCALE_TYPE': 'SCALE_TYPE',
    'SKIN_COLOR': 'SKIN_COLOR',
    'RACE': 'RACE',
    'STATUS': 'STATUS',
    'SPECIALTY': 'SPECIALTY',
    'TEACHING_CATEGORY': 'TEACHING_CATEGORY',
    'TEACHER_STATUS': 'TEACHER_STATUS',
    'CATEGORY': 'CATEGORY',
    'CONSTRUCTION_STATE': 'CONSTRUCTION_STATE',
    'STRUCTURE_SECTOR': 'STRUCTURE_SECTOR',
    'STRUCTURE_MAIN_ACTIVITY': 'STRUCTURE_MAIN_ACTIVITY',
}

STRUCTURE_TYPE = {
    'STRUCTURE_MINED_TYPE': 'MINED',
    'STRUCTURE_DIR_PROVINCIAL_TYPE': 'STRUCTURE_DIR_PROVINCIAL_TYPE',
    'STRUCTURE_DIR_MUNICIPALITY_TYPE': 'STRUCTURE_DIR_MUNICIPALITY_TYPE',
    'STRUCTURE_HOME_TYPE': 'STRUCTURE_HOME_TYPE',
    'STRUCTURE_CAMPAMENT_TYPE': 'STRUCTURE_CAMPAMENT_TYPE',
    'STRUCTURE_PIONER_TYPE': 'STRUCTURE_PIONER_TYPE',
    'STRUCTURE_SCHOOL_TYPE': 'STRUCTURE_SCHOOL_TYPE',
}

RELATIONSHIP_TYPE = {
    'Relationship_Grandparent': 'Grandparent',
    'Relationship_Godson': 'Godson',
    'Relationship_Schoolchild': 'Schoolchild',
    'Relationship_Friend': 'Friend',
    'Relationship_Great_Grandparent': 'Great_Grandparent',
    'Relationship_Great_Grandson': 'Great_Grandson',
    'Relationship_Roommate': 'Roommate',
    'Relationship_Concubine': 'Concubine',
    'Relationship_Concuño': 'Concuño',
    'Relationship_In_Law': 'In_Law',
    'Relationship_Brother-In-Law': 'Brother-In-Law',
    'Relationship_Ex_Husband': 'Ex_Husband',
    'Relationship_Ex_Wife': 'Ex_Wife',
    'Relationship_Stepbrother': 'Stepbrother',
    'Relationship_Brother': 'Brother',
    'Relationship_Sister': 'Sister',
    'Relationship_Stepson': 'Stepson',
    'Relationship_Adopted_Son': 'Adopted_Son',
    'Relationship_Consanguineous_Child': 'Consanguineous_Child',
    'Relationship_Foster_Child': 'Foster_Child',
    'Relationship_Picked_Up_Son': 'Picked_Up_Son',
    'Relationship_Recognized_Son': 'Recognized_Son',
    'Relationship_Stepmother': 'Stepmother',
    'Relationship_Mother': 'Mother',
    'Relationship_Godmother': 'Godmother',
    'Relationship_Husband': 'Husband',
    'Relationship_Half_Brother': 'Half_Brother',
    'Relationship_Wife': 'Wife',
    'Relationship_Baby_Sister': 'Baby_Sister',
    'Relationship_Grandson': 'Grandson',
    'Relationship_Not_Specified': 'Not_Specified',
    'Relationship_Does_Not_Know': 'Does_Not_Know',
    'Relationship_Boyfriend': 'Boyfriend',
    'Relationship_Daughter_In_Law': 'Daughter_In_Law',
    'Relationship_Other_Relationship': 'Other_Relationship',
    'Relationship_Stepfather': 'Stepfather',
    'Relationship_Father': 'Father',
    'Relationship_Godfather': 'Godfather',
    'Relationship_Relative': 'Relative',
    'Relationship_Cousin': 'Cousin',
    'Relationship_Dear': 'Dear',
    'Relationship_Lady': 'Lady',
    'Relationship_Nephew': 'Nephew',
    'Relationship_Father_In_Law': 'Father_In_Law',
    'Relationship_Great_Grandfather': 'Great_Grandfather',
    'Relationship_Great_Great_Grandson': 'Great_Great_Grandson',
    'Relationship_Uncle': 'Uncle',
    'Relationship_Tutor': 'Tutor',
    'Relationship_Son_In_Law': 'Son_In_Law',
    'Relationship_Lover': 'Lover',
    'Relationship_Amasio': 'Amasio',
    'Relationship_Leaning': 'Leaning',
    'Relationship_Comrade': 'Comrade',
    'Relationship_Midwife': 'Midwife',
    'Relationship_Buddy': 'Buddy',
    'Relationship_Partner': 'Partner',
    'Relationship_Consort': 'Consort',
    'Relationship_Spouse': 'Spouse',
    'Relationship_Seasoned': 'Seasoned',
    'Relationship_Family': 'Family',
    'Relationship_Foster_Son': 'Foster_Son',
    'Relationship_Orphan': 'Orphan',
    'Relationship_Boss': 'Boss',
    'Relationship_Lullaby': 'Lullaby',
    'Relationship_None': 'None',
    'Relationship_Nona': 'Nona',
    'Relationship_Dad': 'Dad',
    'Relationship_Couple': 'Couple',
    'Relationship_Single': 'Single',
    'Relationship_Progenitor': 'Progenitor',
    'Relationship_Ward': 'Ward',
    'Relationship_Picked_Up': 'Picked_Up',
    'Relationship_Tata': 'Tata',
    'Relationship_Tutored': 'Tutored'
}

DISCAPACITY_TYPE = {
    'DISCAPACITY_ACHONDROPLASIA': 'ACHONDROPLASIA',
    'DISCAPACITY_ALTERATION_OF_HEARING': 'ALTERATION_OF_HEARING',
    'DISCAPACITY_ALZHEIMER': 'ALZHEIMER',
    'DISCAPACITY_ASTIGMATISM': 'ASTIGMATISM',
    'DISCAPACITY_FRIEDREICH_ATAXIA': 'FRIEDREICH_ATAXIA',
    'DISCAPACITY_SPINAL_MUSCULAR_ATROPHY': 'SPINAL_MUSCULAR_ATROPHY',
    'DISCAPACITY_AUTISM': 'AUTISM',
    'DISCAPACITY_BETA_THALASEMIA': 'BETA_THALASEMIA',
    'DISCAPACITY_WATERFALLS': 'WATERFALLS',
    'DISCAPACITY_BLINDNESS': 'BLINDNESS',
    'DISCAPACITY_ORBITARY_CELLULITE': 'ORBITARY_CELLULITE',
    'DISCAPACITY_CHONDROMALACIA': 'CHONDROMALACIA',
    'DISCAPACITY_HUNTINGTON_CHOREA': 'HUNTINGTON_CHOREA',
    'DISCAPACITY_BIVALVE_AORTA_DEFICIENCY': 'BIVALVE_AORTA_DEFICIENCY',
    'DISCAPACITY_BIPOLAR_DEPRESSION': 'BIPOLAR_DEPRESSION',
    'DISCAPACITY_RETINAL_DETACHMENT': 'RETINAL_DETACHMENT',
    'DISCAPACITY_MELLITUS_DIABETES': 'MELLITUS_DIABETES',
    'DISCAPACITY_HANDICAPPED': 'HANDICAPPED',
    'DISCAPACITY_HANDICAPPED_PHYSICAL_MOTOR': 'HANDICAPPED_PHYSICAL_MOTOR',
    'DISCAPACITY_DYSPLASIA': 'DYSPLASIA',
    'DISCAPACITY_MUSCULAR_DYSTONIA': 'DYSTONIA',
    'DISCAPACITY_CORNEAL_DYSTROPHY': 'CORNEAL_DYSTROPHY',
    'DISCAPACITY_MUSCULAR_DYSTROPHY': 'MUSCULAR_DYSTROPHY',
    'DISCAPACITY_DUCHENNE_MUSCULAR_DYSTROPHY': 'DUCHENNE_MUSCULAR_DYSTROPHY',
    'DISCAPACITY_MYOTONIC_MUSCULAR_DYSTROPHY': 'MYOTONIC_MUSCULAR_DYSTROPHY',
    'DISCAPACITY_FAHR_DISEASE': 'FAHR_DISEASE',
    'DISCAPACITY_STRUMPELL_DISEASE': 'STRUMPELL_DISEASE',
    'DISCAPACITY_EPILEPSY': 'EPILEPSY',
    'DISCAPACITY_SCLERODERMA': 'SCLERODERMA',
    'DISCAPACITY_MULTIPLE_SCLEROSIS': 'MULTIPLE_SCLEROSIS',
    'DISCAPACITY_SPINA_BIFIDA': 'SPINA_BIFIDA',
    'DISCAPACITY_SCHIZOPHRENIA': 'SCHIZOPHRENIA',
    'DISCAPACITY_PHENYLKETONURIA': 'PHENYLKETONURIA',
    'DISCAPACITY_GENUSBALDUS': 'GENUSBALDUS',
    'DISCAPACITY_OPEN_ANGLE_GLAUCOMA': 'OPEN_ANGLE_GLAUCOMA',
    'DISCAPACITY_CLOSE_ANGLE_GLAUCOMA': 'CLOSE_ANGLE_GLAUCOMA',
    'DISCAPACITY_SECONDARY_GLAUCOMA': 'SECONDARY_GLAUCOMA',
    'DISCAPACITY_HEMIANOPIA': 'HEMIANOPIA',
    'DISCAPACITY_HEMIPLEGIA': 'HEMIPLEGIA',
    'DISCAPACITY_HEARING_LOSS': 'HEARING_LOSS',
    'DISCAPACITY_IMMUNOSUPPRESSED': 'IMMUNOSUPPRESSED',
    'DISCAPACITY_LEUKEMIA': 'LEUKEMIA',
    'DISCAPACITY_CORNEAL_LEUKOMA': 'CORNEAL_LEUKOMA',
    'DISCAPACITY_PARKINSON_DISEASE': 'PARKINSON_DISEASE',
    'DISCAPACITY_TRANSVERSE_MYELITIS': 'TRANSVERSE_MYELITIS',
    'DISCAPACITY_MYOPIA_WITH_DEGENERATIVE_LESIONS': 'MYOPIA_WITH_DEGENERATIVE_LESIONS',
    'DISCAPACITY_RETROBULBAR_NEURITIS': 'RETROBULBAR_NEURITIS',
    'DISCAPACITY_OSTEOGENESIS_IMPERFECTA_CRYSTAL_BONES': 'OSTEOGENESIS_IMPERFECTA_CRYSTAL_BONES',
    'DISCAPACITY_CEREBRAL_PALSY': 'CEREBRAL_PALSY',
    'DISCAPACITY_PARANOIA': 'PARANOIA',
    'DISCAPACITY_PARAPLEGIA': 'PARAPLEGIA',
    'DISCAPACITY_POLIOMYELITIS': 'POLIOMYELITIS',
    'DISCAPACITY_PRESBYCUSIS': 'PRESBYCUSIS',
    'DISCAPACITY_ORGANIC_PSYCHOSYS': 'ORGANIC_PSYCHOSYS',
    'DISCAPACITY_DIABETIC_RETINOPATHY': 'DIABETIC_RETINOPATHY',
    'DISCAPACITY_RETINITIS_PIGMENTOSA': 'RETINITIS_PIGMENTOSA',
    'DISCAPACITY_CORNELIA_DE_LANGE_SYNDROME': 'CORNELIA_DE_LANGE_SYNDROME',
    'DISCAPACITY_CUSHING_SYNDROME': 'CUSHING_SYNDROME',
    'DISCAPACITY_DOWN_SYNDROME': 'DOWN_SYNDROME',
    'DISCAPACITY_CHRONIC_FATIGUE_SYNDROME': 'CHRONIC_FATIGUE_SYNDROME',
    'DISCAPACITY_GUILLES_DE_TOURETTE_SYNDROME': 'GUILLES_DE_TOURETTE_SYNDROME',
    'DISCAPACITY_GORLIN_SYNDROME': 'GORLIN_SYNDROME',
    'DISCAPACITY_GUILLAIN_BARRE_SYNDROME': 'GUILLAIN_BARRE_SYNDROME',
    'DISCAPACITY_ATTENTION_DEFICIT_SYNDROME': 'ATTENTION_DEFICIT_SYNDROME',
    'DISCAPACITY_CARPAL_TUNNEL_SYNDROME': 'CARPAL_TUNNEL_SYNDROME',
    'DISCAPACITY_PRADER_WILLI_SYNDROME': 'PRADER_WILLI_SYNDROME',
    'DISCAPACITY_RETT_SYNDROME': 'RETT_SYNDROME',
    'DISCAPACITY_SJOGREN_SYNDROME': 'SJOGREN_SYNDROME',
    'DISCAPACITY_STEVENS_JOHNSON_SYNDROME': 'STEVENS_JOHNSON_SYNDROME',
    'DISCAPACITY_TURNER_SYNDROME': 'TURNER_SYNDROME',
    'DISCAPACITY_USHER_SYNDROME': 'USHER_SYNDROME',
    'DISCAPACITY_WEST_SYNDROME': 'WEST_SYNDROME',
    'DISCAPACITY_WILLIAM_SYNDROME': 'WILLIAM_SYNDROME',
    'DISCAPACITY_NEPHROTIC_SYNDROME': 'NEPHROTIC_SYNDROME',
    'DISCAPACITY_X_FRAGILE_SYNDROME': 'X_FRAGILE_SYNDROME',
    'DISCAPACITY_SITUS_INVERSUS': 'SITUS_INVERSUS',
    'DISCAPACITY_DEAFNESS': 'DEAFNESS',
    'DISCAPACITY_TETRAPLEGIA': 'TETRAPLEGIA',
    'DISCAPACITY_THROMBOPATHY': 'THROMBOPATHY',
}

SPECIALITY_TYPE = {
    'SPECIALITY_PRIMARY': 'SPECIALITY_PRIMARY',
    'SPECIALITY_SPECIAL': 'SPECIALITY_SPECIAL',
}

EYES_COLOR_TYPE = {
    'EYES_BLACK': 'BLACK',
    'EYES_BLUE': 'BLUE',
    'EYES_GREEN': 'GREEN',
}

HAIR_COLOR_TYPE = {
    'HAIR_BLACK': 'BLACK',
    'HAIR_BLONDE': 'BLONDE',
}

GENDER_TYPE = {
    'GENDER_MALE': 'MALE',
    'GENDER_FEMALE': 'FEMALE',
}

SKIN_COLOR_TYPE = {
    'SKIN_BLACK': 'BLACK',
    'SKIN_WHITE': 'WHITE',
    'SKIN_BROW_LIGHT': 'BROWN_LIGHT',
    'SKIN_BROWN_DARK': 'BROWN_DARK',
}

RACE_TYPE = {
    'RACE_WHITE': 'RACE_WHITE',
    'RACE_BLACK': 'RACE_BLACK',
    'RACE_BROWN': 'RACE_BROWN',
}

STUDENT_STATUS_TYPE = {
    'STATUS_NEW': 'STATUS_NEW',
    'STATUS_PROMOTED': 'STATUS_PROMOTED',
    'STATUS_REP': 'STATUS_REP',
    'STATUS_REINCORPORATED': 'STATUS_REINCORPORATED',
    'STATUS_READMITTED': 'STATUS_READMITTED',
    'STATUS_COMPLEMENTARY': 'STATUS_COMPLEMENTARY',
}

TEACHER_SPECIALITY_TYPE = {
    'SPECIALTY_PRIMARY': 'SPECIALTY_PRIMARY',
    'SPECIALTY_LICENCED': 'SPECIALTY_LICENCED',
}

TEACHING_CATEGORY_TYPE = {
    'CATEGORY_INSTRUCTOR': 'CATEGORY_INSTRUCTOR',
    'CATEGORY_ASSISTANT': 'CATEGORY_ASSISTANT',
    'CATEGORY_AUXILIAR': 'CATEGORY_AUXILIAR',
    'CATEGORY_TITULAR': 'CATEGORY_TITULAR',
}

TEACHER_STATUS_TYPE = {
    'STATUS_FIXED': 'STATUS_FIXED',
    'STATUS_HIRED': 'STATUS_HIRED',
    'STATUS_STUDENT_TEACHER': 'STATUS_STUDENT_TEACHER',
}

# PERSON_CATEGORY_TYPE = {
#     'PERSON_TEACHER': 'PERSON_TEACHER',
#     'PERSON_WORKER': 'PERSON_WORKER',
#     'PERSON_STUDENT': 'PERSON_STUDENT',
# }

PERSON_CATEGORY_TYPE = (
    (PERSON_TEACHER, _(PERSON_TEACHER)),
    (PERSON_WORKER, _(PERSON_WORKER)),
    (PERSON_STUDENT, _(PERSON_STUDENT)),
)

STRUCTURE_SECTOR_TYPE = {
    'SECTOR_RURAL': 'SECTOR_RURAL',
    'SECTOR_URBANO': 'SECTOR_URBANO',
}

BUILDING_CONSTRUCTIVE_STATE = {
    'STATE_GOOD': 'STATE_GOOD',
    'STATE_REGULAR': 'STATE_REGULAR',
    'STATE_BAD': 'STATE_BAD',
    'STATE_UNDEFINED': 'STATE_UNDEFINED',
}

STRUCTURE_ACTIVITY_TYPE = {
    'ACTIVITY_AUTISM': 'ACTIVITY_AUTISM',
    'ACTIVITY_LOW_VISION': 'ACTIVITY_LOW_VISION',
    'ACTIVITY_BLIND': 'ACTIVITY_BLIND',
    'ACTIVITY_KINDER': 'ACTIVITY_KINDER',
    'ACTIVITY_INTELLECTUAL_DISABILITY': 'ACTIVITY_INTELLECTUAL_DISABILITY',
    'ACTIVITY_CPT': 'ACTIVITY_CPT',
    'ACTIVITY_DAY': 'ACTIVITY_DAY',
    'ACTIVITY_LANGUAGE': 'ACTIVITY_LANGUAGE',
    'ACTIVITY_PROFESSION_SCHOOL': 'ACTIVITY_PROFESSION_SCHOOL',
    'ACTIVITY_COUNTRYSIDE_SCHOOL': 'ACTIVITY_COUNTRYSIDE_SCHOOL',
    'ACTIVITY_PEDAGOGICAL_SCHOOL': 'ACTIVITY_PEDAGOGICAL_SCHOOL',
    'ACTIVITY_AMBLIOPES': 'ACTIVITY_AMBLIOPES',
    'ACTIVITY_FACULTY_COUNTRYSIDE': 'ACTIVITY_FACULTY_COUNTRYSIDE',
    'ACTIVITY_PRE_SCHOOL_EXACT_SCIENCE': 'ACTIVITY_PRE_SCHOOL_EXACT_SCIENCE',
    'ACTIVITY_COUNTRYSIDE_PRE': 'ACTIVITY_COUNTRYSIDE_PRE',
    'ACTIVITY_URBAN_PRE': 'ACTIVITY_URBAN_PRE',
    'ACTIVITY_LIMIT_MOVEMENT': 'ACTIVITY_LIMIT_MOVEMENT',
    'ACTIVITY_PRIMARY': 'ACTIVITY_PRIMARY',
    'ACTIVITY_RETARD': 'ACTIVITY_RETARD',
    'ACTIVITY_METAL_RETARD': 'ACTIVITY_METAL_RETARD',
    'ACTIVITY_COUNTRYSIDE_SECONDARY': 'ACTIVITY_COUNTRYSIDE_SECONDARY',
    'ACTIVITY_URBAN_SECONDARY': 'ACTIVITY_URBAN_SECONDARY',
    'ACTIVITY_WORKER_SECONDARY': 'ACTIVITY_WORKER_SECONDARY',
    'ACTIVITY_DEFT_BLIND': 'ACTIVITY_DEFT_BLIND',
    'ACTIVITY_HIPOCAUSICOS': 'ACTIVITY_HIPOCAUSICOS',
    'ACTIVITY_CONDUCT_1ra': 'ACTIVITY_CONDUCT_1ra',
    'ACTIVITY_CONDUCT_2da': 'ACTIVITY_CONDUCT_2da',
    'ACTIVITY_COMMUNICATION_PROBLEM': 'ACTIVITY_COMMUNICATION_PROBLEM',
}

REGIME_TYPE = {
    'REGIMEN_NOT_DEFINED': 'REGIMEN_NOT_DEFINED',
    'REGIMEN_EXTERNAL': 'REGIMEN_EXTERNAL',
    'REGIMEN_SEMI_INTERNAL': 'REGIMEN_SEMI_INTERNAL',
    'REGIMEN_INTERNAL': 'REGIMEN_INTERNAL',
}

CONSTRUCTION_TYPE = {
    'CONSTRUCTION_DEFAULT': 'CONSTRUCTION_DEFAULT',
    'CONSTRUCTION_ADAPTED_HOUSE': 'CONSTRUCTION_ADAPTED_HOUSE',
    'CONSTRUCTION_CONVENTIONAL': 'CONSTRUCTION_CONVENTIONAL',
    'CONSTRUCTION_GIRON': 'CONSTRUCTION_GIRON',
    'CONSTRUCTION_WOOD': 'CONSTRUCTION_WOOD',
    'CONSTRUCTION_ANOTHER_KIND': 'CONSTRUCTION_ANOTHER_KIND',
    'CONSTRUCTION_SANDINO': 'CONSTRUCTION_SANDINO',
    'CONSTRUCTION_INCLINED_BEAM': 'CONSTRUCTION_INCLINED_BEAM',
}

HEALTH_COUNCIL_TYPE = {
    'HEALTH_COUNCIL_TYPE': 'HEALTH_COUNCIL_TYPE',
}

ATTENTION_AREA_TYPE = {
    'ATTENTION_AREA_TYPE': 'ATTENTION_AREA_TYPE',
}

ORGANISM_TYPE = {
    'ORGANISM_MINED': 'ORGANISM_MINED',
    'ORGANISM_INDER': 'ORGANISM_INDER',
    'ORGANISM_MINCULT': 'ORGANISM_MINCULT',
}

PATRIMONY_TYPE = {
    'PATRIMONY_LOCAL': 'PATRIMONY_LOCAL',
}

SESSION_TYPE = {
    'SESSION_MORNING': 'SESSION_MORNING',
    'SESSION_AFTERNOON': 'SESSION_AFTERNOON',
    'SESSION_DOUBLE': 'SESSION_DOUBLE',
}

EDUCATION_LEVEL_TYPE = {
    'LEVEL_NO_LEVEL': 'LEVEL_NO_LEVEL',
    'LEVEL_PRIMARY': 'LEVEL_PRIMARY',
    'LEVEL_BASIC': 'LEVEL_MIDDLE',
    'LEVEL_UPPER_MIDDLE': 'LEVEL_UPPER_MIDDLE',
}

EDUCATION_TYPE = {
    'EDUCATION_CHILD': 'EDUCATION_CHILD',
    'EDUCATION_EARLY_CHILDHOOD': 'EDUCATION_EARLY_CHILDHOOD',
    'EDUCATION_PRIMARY': 'EDUCATION_PRIMARY',
    'EDUCATION_BASIC_SECONDARY': 'EDUCATION_BASIC_SECONDARY',
    'EDUCATION_SPECIAL': 'EDUCATION_SPECIAL',
    'EDUCATION_PRE_UNIVERSITY': 'EDUCATION_PRE_UNIVERSITY',
    'EDUCATION_PEDAGOGICAL_TRAINING': 'EDUCATION_PEDAGOGICAL_TRAINING',
    'EDUCATION_ADULTS': 'EDUCATION_ADULTS',
    'EDUCATION_PROFESSIONAL_TECHNIQUE': 'EDUCATION_PROFESSIONAL_TECHNIQUE',
}

ACRONYM_TYPE = {
    'ACRONYM_CI_TYPE': 'ACRONYM_CI_TYPE',
}

COUNTRY_TYPE = {
    'COUNTRY_CUBA': 'COUNTRY_CUBA',
}

CHARACTERISTIC_TYPE = {
    'CHARACTERISTIC_TYPE_AMOUNT': 'CHARACTERISTIC_TYPE_AMOUNT',
    'CHARACTERISTIC_TYPE_EXISTENCE': 'CHARACTERISTIC_TYPE_EXISTENCE',
}

CHARACTERISTIC_CATEGORY_TYPE = {
    'CHARACTERISTIC_CATEGORY_STRUCTURE': 'CHARACTERISTIC_CATEGORY_STRUCTURE',
    'CHARACTERISTIC_CATEGORY_BUILDING': 'CHARACTERISTIC_CATEGORY_BUILDING',
    'CHARACTERISTIC_CATEGORY_EDUCATIONAL_CENTER': 'CHARACTERISTIC_CATEGORY_EDUCATIONAL_CENTER',
}

LOCATION_TYPE = {
    'LOCATION_1': 'LOCATION_1',
}

POPULAR_COUNCIL_TYPE = {
    'POPULAR_COUNCIL_1': 'POPULAR_COUNCIL_1',
}

CIVIL_STATE_TYPE = {
    'STATE_SINGLE': 'STATE_SINGLE',
    'STATE_MARRIED': 'STATE_MARRIED',
    'STATE_DIVORCED': 'STATE_DIVORCED',
}

SCHOLAR_LEVEL_TYPE = {
    'SCHOLAR_LEVEL_SUPERIOR': 'SCHOLAR_LEVEL_SUPERIOR',
    'SCHOLAR_LEVEL_MEDIUM': 'SCHOLAR_LEVEL_MEDIUM',
    'SCHOLAR_LEVEL_PRIMARY': 'SCHOLAR_LEVEL_PRIMARY',
}

PROFESSION_TYPE = {
    'PROFESSION_ELECTRICIAN': 'PROFESSION_ELECTRICIAN',
    'PROFESSION_CARPENTER': 'PROFESSION_CARPENTER',
    'PROFESSION_GARDENER': 'PROFESSION_GARDENER',
    'PROFESSION_BRICKLAYER': 'PROFESSION_BRICKLAYER',
    'PROFESSION_CHEF': 'PROFESSION_CHEF',
    'PROFESSION_DRIVER': 'PROFESSION_DRIVER',
}

ACADEMIC_GRADE_TYPE = {
    'ACADEMIC_GRADE_FIRST': 'ACADEMIC_GRADE_FIRST',
    'ACADEMIC_GRADE_SECOND': 'ACADEMIC_GRADE_SECOND',
    'ACADEMIC_GRADE_THIRD': 'ACADEMIC_GRADE_THIRD',
    'ACADEMIC_GRADE_FORTH': 'ACADEMIC_GRADE_FORTH',
    'ACADEMIC_GRADE_FIFTH': 'ACADEMIC_GRADE_FIFTH',
    'ACADEMIC_GRADE_SIXTH': 'ACADEMIC_GRADE_SIXTH',
}

INVESTIGATIVE_CATEGORY_TYPE = {
    'INVESTIGATIVE_CATEGORY_A': 'INVESTIGATIVE_CATEGORY_A',
    'INVESTIGATIVE_CATEGORY_B': 'INVESTIGATIVE_CATEGORY_B',
    'INVESTIGATIVE_CATEGORY_C': 'INVESTIGATIVE_CATEGORY_C',
}
DISEASE_TYPE = {
    'DISEASE_ASTHMA': 'DISEASE_ASTHMA',
    'DISEASE_DIABETES': 'DISEASE_DIABETES',
    'DISEASE_ALZHEIMER': 'DISEASE_ALZHEIMER',
    'DISEASE_POLIOMYELITIS': 'DISEASE_POLIOMYELITIS',
    'DISEASE_AIDS': 'DISEASE_AIDS',
    'DISEASE_CANCER': 'DISEASE_CANCER',
}

ORPHAN_TYPE = {
    'ORPHAN_FATHER': 'ORPHAN_FATHER',
    'ORPHAN_MOTHER': 'ORPHAN_MOTHER',
    'ORPHAN_BOTH_PARENTS': 'ORPHAN_BOTH_PARENTS',
}

POLITIC_ORGANIZATION_TYPE = {
    'POLITIC_ORGANIZATION_UJC': 'POLITIC_ORGANIZATION_UJC',
    'POLITIC_ORGANIZATION_PCC': 'POLITIC_ORGANIZATION_PCC',
}

MASSIVE_ORGANIZATION_TYPE = {
    'MASSIVE_ORGANIZATION_CDR': 'MASSIVE_ORGANIZATION_CDR',
    'MASSIVE_ORGANIZATION_CTC': 'MASSIVE_ORGANIZATION_CTC',
    'MASSIVE_ORGANIZATION_FMC': 'MASSIVE_ORGANIZATION_FMC',
    'MASSIVE_ORGANIZATION_OPJM': 'MASSIVE_ORGANIZATION_OPJM',
    'MASSIVE_ORGANIZATION_FEEM': 'MASSIVE_ORGANIZATION_FEEM',
    'MASSIVE_ORGANIZATION_FEU': 'MASSIVE_ORGANIZATION_FEU',
}

CATEGORY_OCCUPATION_TYPE = {
    'OCCUPATION_SECRETARY': 'OCCUPATION_SECRETARY',
}

RESPONSIBILITY_TYPE = {
    'RESPONSIBILITY_SECRETARY': 'RESPONSIBILITY_SECRETARY',
}

STRUCTURE_CATEGORY_TYPE = {
    'CATEGORY_ORGANIZATIONAL': 'CATEGORY_ORGANIZATIONAL',
}

STRUCTURE_LEVEL_TYPE = {
    'LEVEL_NATIONAL': 'LEVEL_NATIONAL',
}

VINCULATION_TYPE = {
    'VINCULATION_CULTURAL': 'VINCULATION_CULTURAL',
}

BRANCH_TYPE = {
    'BRANCH_ADMIN': 'BRANCH_ADMIN',
}

LEVEL_TITTLE_TYPE = {
    'LEVEL_PROVINCIAL': 'LEVEL_PROVINCIAL',
}

FAMILY_TYPE = {
    'FAMILY_MIDDLE': 'FAMILY_MIDDLE',
}

PROCEDURE_STATE_TYPE = {
    'PROCEDURE_REGISTERED': 'PROCEDURE_REGISTERED',
    'PROCEDURE_LOCATED': 'PROCEDURE_LOCATED',
    'PROCEDURE_MATRICULATED': 'PROCEDURE_MATRICULATED',
    'PROCEDURE_MOVED': 'PROCEDURE_MOVED',
    'PROCEDURE_CHANGED': 'PROCEDURE_CHANGED',
}

SCHOOL_SITUATION_TYPE = {
    'SITUATION_NEW_ENTRY': 'SITUATION_NEW_ENTRY',
    'SITUATION_REPEATING': 'SITUATION_REPEATING',
    'SITUATION_PROMOTED': 'SITUATION_PROMOTED',
    'SITUATION_RE_ENTRY': 'SITUATION_RE_ENTRY',
    'SITUATION_REINCORPORATION': 'SITUATION_REINCORPORATION',
}
EMPLOYMENT_RELATIONSHIP_TYPE = {
    'RELATIONSHIP_NO_LINKS': 'RELATIONSHIP_NO_LINKS',
    'RELATIONSHIP_LINKED_STATE_SECTOR': 'RELATIONSHIP_LINKED_STATE_SECTOR',
    'RELATIONSHIP_LINKED_NON_STATE_SECTOR': 'RELATIONSHIP_LINKED_NON_STATE_SECTOR',
}

LABORAL_SECTOR_TYPE = {
    'SECTOR_HEALTH': 'SECTOR_HEALTH',
    'SECTOR_AGRICULTURE_AND_LIVESTOCK': 'SECTOR_AGRICULTURE_AND_LIVESTOCK',
    'SECTOR_EDUCATION': 'SECTOR_EDUCATION',
    'SECTOR_MILITARY': 'SECTOR_MILITARY',
    'SECTOR_COMMERCE': 'SECTOR_COMMERCE',
    'SECTOR_CONSTRUCTION': 'SECTOR_CONSTRUCTION',
    'SECTOR_SERVICES': 'SECTOR_SERVICES',
    'SECTOR_INFORMATION_AND_COMMUNICATION': 'SECTOR_INFORMATION_AND_COMMUNICATION',
    'SECTOR_TRANSPORT': 'SECTOR_TRANSPORT',
    'SECTOR_ADMINISTRATION_AND_MANAGEMENT': 'SECTOR_ADMINISTRATION_AND_MANAGEMENT',
    'SECTOR_FINANCE_AND_INSURANCE': 'SECTOR_FINANCE_AND_INSURANCE',
    'SECTOR_HOTELS_AND_TOURISM': 'SECTOR_HOTELS_AND_TOURISM',
    'SECTOR_FISHERIES_AND_AQUACULTURE': 'SECTOR_FISHERIES_AND_AQUACULTURE',
    'SECTOR_INDUSTRY': 'SECTOR_INDUSTRY',
    'SECTOR_TELECOMMUNICATIONS': 'SECTOR_TELECOMMUNICATIONS',
}

SOCIAL_ORIGIN_TYPE = {
    'ORIGIN_ADMINISTRATIVE': 'ORIGIN_ADMINISTRATIVE',
    'ORIGIN_TEACHER_OR_PROFESSOR': 'ORIGIN_TEACHER_OR_PROFESSOR',
    'ORIGIN_FARMER': 'ORIGIN_FARMER',
    'ORIGIN_WORKER': 'ORIGIN_WORKER',
    'ORIGIN_UNKNOWN': 'ORIGIN_UNKNOWN',
    'ORIGIN_LEADER': 'ORIGIN_LEADER',
    'ORIGIN_RETIRED': 'ORIGIN_RETIRED',
    'ORIGIN_HOUSEWIFE': 'ORIGIN_HOUSEWIFE',
    'ORIGIN_SERVICES_WORKER': 'ORIGIN_SERVICES_WORKER',
    'ORIGIN_PROFESSIONAL': 'ORIGIN_PROFESSIONAL',
    'ORIGIN_TECHNICIAN': 'ORIGIN_TECHNICIAN',
}

EDUCATION_TYPIFICATION_TYPE = {
    'TYPIFICATION_EDUCATE_YOUR_CHILD_PROGRAM': 'TYPIFICATION_EDUCATE_YOUR_CHILD_PROGRAM',
    'TYPIFICATION_CHILDREN_TEACHING': 'TYPIFICATION_CHILDREN_TEACHING',
    'TYPIFICATION_LITERACY': 'TYPIFICATION_LITERACY',
    'TYPIFICATION_LANGUAGES_TEACHING': 'TYPIFICATION_LANGUAGES_TEACHING',
    'TYPIFICATION_PRIMARY_TEACHING': 'TYPIFICATION_PRIMARY_TEACHING',
    'TYPIFICATION_PEASANT_WORKER_TEACHING': 'TYPIFICATION_PEASANT_WORKER_TEACHING',
    'TYPIFICATION_TRADES_TEACHING': 'TYPIFICATION_TRADES_TEACHING',
    'TYPIFICATION_SECONDARY': 'TYPIFICATION_SECONDARY',
    'TYPIFICATION_PRE_UNIVERSITY': 'TYPIFICATION_PRE_UNIVERSITY',
    'TYPIFICATION_SPECIAL_TEACHING': 'TYPIFICATION_SPECIAL_TEACHING',
    'TYPIFICATION_PEASANT_WORKER_SECONDARY': 'TYPIFICATION_PEASANT_WORKER_SECONDARY',
    'TYPIFICATION_POLYTECHNICAL_TEACHING': 'TYPIFICATION_POLYTECHNICAL_TEACHING',
    'TYPIFICATION_PEDAGOGICAL_TRAINING': 'TYPIFICATION_PEDAGOGICAL_TRAINING',
    'TYPIFICATION_PEDAGOGICAL_TEACHING': 'TYPIFICATION_PEDAGOGICAL_TEACHING',
    'TYPIFICATION_PEASANT_WORKERS_FACULTY': 'TYPIFICATION_PEASANT_WORKERS_FACULTY',
}

# ------------------- WORKER STATE TYPES CHOICES ----------------------

CONST_WORKER_STATE_ACTIVE = 'ACTIVE'
CONST_WORKER_STATE_INACTIVE = 'INACTIVE'
CONST_WORKER_STATE_UNSUBSCRIBED = 'UNSUBSCRIBED'
CONST_WORKER_STATE_TRANSFER = 'TRANSFER'
CONST_WORKER_STATE_OTHER_FUNCTIONS = 'OTHER_FUNCTIONS'
CONST_WORKER_STATE_CHANGE = 'CHANGE'

WORKER_STATE_TYPE = (
    (CONST_WORKER_STATE_ACTIVE, _(CONST_WORKER_STATE_ACTIVE)),
    (CONST_WORKER_STATE_INACTIVE, _(CONST_WORKER_STATE_INACTIVE)),
    (CONST_WORKER_STATE_UNSUBSCRIBED, _(CONST_WORKER_STATE_UNSUBSCRIBED)),
    (CONST_WORKER_STATE_TRANSFER, _(CONST_WORKER_STATE_TRANSFER)),
    (CONST_WORKER_STATE_OTHER_FUNCTIONS, _(CONST_WORKER_STATE_OTHER_FUNCTIONS)),
    (CONST_WORKER_STATE_CHANGE,_(CONST_WORKER_STATE_CHANGE))
)

# ------------------- WORKER UNSUBSCRIBEMENT TYPES CHOICES ----------------------

CONST_WORKER_UNSUBSCRIBEMENT_TRANSFER = 'TRANSFER'
CONST_WORKER_UNSUBSCRIBEMENT_UNSUBSCRIBE = 'UNSUBSCRIBE'

WORKER_UNSUBSCRIBEMENT_TYPE = (
    (CONST_WORKER_UNSUBSCRIBEMENT_TRANSFER, _(CONST_WORKER_UNSUBSCRIBEMENT_TRANSFER)),
    (CONST_WORKER_UNSUBSCRIBEMENT_UNSUBSCRIBE, _(CONST_WORKER_UNSUBSCRIBEMENT_UNSUBSCRIBE))
)